[tool.poetry]
name = "symphony-api-client-python"
version = "2.0.dev0"
description = "Symphony Bot Development Kit for Python"
authors = ["Symphony Platform Solutions <platformsolutions@symphony.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["*.egg", ".*", "build", "dist", "venv", "legacy"]

