version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: poetry install

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: Run pylint
          command: poetry run pylint symphony tests

      - run:
          name: Run tests with coverage
          command: poetry run pytest

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      - store_artifacts:
          path: htmlcov
