version: 2.1

orbs:
  snyk: snyk/snyk@0.0.12

workflows:
  build-workflow:
    jobs:
      - build
      - snyk:
          context:
            - devx
          filters:
            branches:
              only:
                - "master"
                - "2.0"

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: poetry install

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: Run pylint
          command: poetry run pylint symphony tests

      - run:
          name: Run tests with coverage
          command: poetry run pytest

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      - store_artifacts:
          path: htmlcov

  snyk:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: poetry install

      - snyk/scan:
          severity-threshold: high
