version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout

      - run:
          name: Install Python dependencies
          command: pip3 install -e .

      - run:
          name: Build
          command: python3 setup.py test
