name: build

on:
  push:
    branches-ignore: [ "2.0" ]
  pull_request:
    branches-ignore: [ "2.0" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip3 install -e .

      - name: Run tests
        run: python3 setup.py test
