name: pylint

on:
  pull_request:
    branches: [ "2.0" ]

jobs:
  build:
    name: pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Pylint
        uses: github/super-linter@v3
        env:
          VALIDATE_PYTHON_PYLINT: true
          DEFAULT_BRANCH: "2.0"
          LINTER_RULES_PATH: /
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
