name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: "Release"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: poetry run pytest

      - name: publish
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: poetry publish --build --username "$PYPI_USERNAME" --password "$PYPI_PASSWORD"
